/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/sword.glb -o src/components/Sword.jsx -r public 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Sword(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/sword.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    actions["Armature|mixamo.com|Layer0"].reset().fadeIn(0.5).play()
    return () => actions["Armature|mixamo.com|Layer0"].fadeOut(0.5);
  },[])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Maria_J_J_Ong" geometry={nodes.Maria_J_J_Ong.geometry} material={materials.MariaMat} skeleton={nodes.Maria_J_J_Ong.skeleton} />
          <skinnedMesh name="Maria_sword" geometry={nodes.Maria_sword.geometry} material={materials.MariaMat} skeleton={nodes.Maria_sword.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/sword.glb')
